# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LDLTsolver_new <- function() {
    .Call('_RGCCA_LDLTsolver_new', PACKAGE = 'RGCCA')
}

LDLTsolver_compute <- function(ptr, L) {
    invisible(.Call('_RGCCA_LDLTsolver_compute', PACKAGE = 'RGCCA', ptr, L))
}

LDLTsolver_solve <- function(ptr, b) {
    .Call('_RGCCA_LDLTsolver_solve', PACKAGE = 'RGCCA', ptr, b)
}

